# Generated by Django 2.2.10 on 2021-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_amountdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amountDue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
