# Generated by Django 2.2.10 on 2021-07-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_amountdue'),
        ('matchpayments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsdata',
            name='playerspaid',
            field=models.ManyToManyField(blank=True, related_name='paid', to='users.Profile'),
        ),
    ]
