# Generated by Django 2.2.10 on 2021-07-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_amountdue'),
        ('matchpayments', '0002_paymentsdata_playerspaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paymentsdata', models.ManyToManyField(blank=True, to='matchpayments.PaymentsData')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
