# Generated by Django 2.2.10 on 2021-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='paymentsdata',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='matches',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
