# Generated by Django 2.2.10 on 2021-07-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0004_auto_20210726_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Paid')], default='Pending', max_length=14),
        ),
    ]
