# Generated by Django 2.2.10 on 2021-07-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0005_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1, help_text='User posted reviews and categories are subject for approval.     Only entries with live status will be publicly displayed.'),
        ),
    ]
