# Generated by Django 2.2.10 on 2021-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0008_auto_20210727_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='matches',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='request', to='matchpayments.PaymentsData'),
        ),
    ]
