# Generated by Django 2.2.10 on 2021-10-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_amountdue'),
        ('matchpayments', '0010_paymentrequest_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountdue', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('matches', models.ManyToManyField(blank=True, to='matchpayments.PaymentsData')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
