# Generated by Django 2.2.10 on 2021-10-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0011_playerspaymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerspaymentdetails',
            name='amountdue',
        ),
    ]
