# Generated by Django 2.2.10 on 2022-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0012_remove_playerspaymentdetails_amountdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerspaymentdetails',
            name='owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
