# Generated by Django 2.2.10 on 2021-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210324_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amountDue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
