# Generated by Django 2.2.10 on 2021-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_amountdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amountDue',
            field=models.IntegerField(default=0),
        ),
    ]
