# Generated by Django 2.2.10 on 2021-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210708_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amountDue',
        ),
    ]
