# Generated by Django 2.2.10 on 2021-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_amountdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amountDue',
            field=models.IntegerField(default=0),
        ),
    ]
