# Generated by Django 2.2.10 on 2021-07-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210709_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amountDue',
        ),
    ]
