# Generated by Django 2.2.10 on 2021-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_remove_profile_amountdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('datespent', models.DateField(verbose_name='Date Spent')),
                ('players', models.ManyToManyField(blank=True, to='users.Profile')),
            ],
        ),
    ]
