# Generated by Django 2.2.10 on 2021-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0007_auto_20210727_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1),
        ),
    ]
