# Generated by Django 2.2.10 on 2021-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0009_auto_20210822_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
