# Generated by Django 2.2.10 on 2022-01-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchpayments', '0013_playerspaymentdetails_owed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerspaymentdetails',
            name='owed',
        ),
    ]
